---
language: python
python: "2.7"

dist: trusty
sudo: required
services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python-pip
  - docker pull ubuntu:latest
  - docker run --name test -di ubuntu | tee container_id
  - docker exec $(cat container_id) apt-get update
  - docker exec $(cat container_id) apt-get install -y python ca-certificates

install:
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' > ansible.cfg
  - pip install ansible-lint
  - docker version

script:
  - ansible-playbook -i localhost, --syntax-check tests/test.yml
  - ansible-lint tests/test.yml
  - ansible-playbook -i test, tests/test.yml

notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

