---

- name: miniconda installer is downloaded
  get_url:
    url="https://repo.continuum.io/miniconda/{{ miniconda_installer }}"
    dest="/tmp/{{ miniconda_installer }}"
    checksum="{{ miniconda_installer_checksum }}"
    force={{ 'yes' if miniconda_installer_checksum == '' else 'no' }}
    mode=0755

- name: directory {{ miniconda_prefix | dirname }} is exists
  file:
    path="{{ miniconda_prefix | dirname }}"
    state=directory

- name: bzip2 is installed
  apt:
    name=bzip2
    state=present
  when: ansible_os_family == "Debian"

- name: miniconda is installed
  shell:
    '"/tmp/{{ miniconda_installer}}" -b -p "{{ miniconda_prefix }}"'
  args:
    creates: "{{ miniconda_prefix }}"
    executable: /bin/bash

- name: miniconda is up-to-date
  command: '"{{ miniconda_prefix }}/bin/conda" update conda -y -q'
  register: miniconda_update
  when: miniconda_update_conda
  changed_when: '"All requested packages already installed" in miniconda_update'

- name: conda environment file /tmp/{{ miniconda_env.name }}-environment.yml is created
  copy:
    content="{{ miniconda_env | to_yaml }}"
    dest="/tmp/{{ miniconda_env.name }}-environment.yml"
  when: miniconda_env != ''

- include: environment.yml
  when: miniconda_env != ''
